// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ILAK.API.CodeGenerate.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class AppConfigTemplate : AppConfigTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<configuration>\r\n    <startup> \r\n        " +
                    "<supportedRuntime version=\"v4.0\" sku=\".NETFramework,Version=v4.5\" />\r\n    </star" +
                    "tup>\r\n\t<connectionStrings>\r\n    <add name=\"connStr\" connectionString=\"");
            
            #line 14 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HYDAPIConnString));
            
            #line default
            #line hidden
            this.Write("\" />\r\n  </connectionStrings>\r\n  <system.serviceModel>\r\n    <services>\r\n\t");
            
            #line 18 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
 foreach (var item in ProjOption.Interfaces) { 
            
            #line default
            #line hidden
            this.Write("      <service behaviorConfiguration=\"TempRestHostSerivce.SB");
            
            #line 19 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IntfCode));
            
            #line default
            #line hidden
            this.Write("\" name=\"TempRestHostService.Service");
            
            #line 19 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IntfCode));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <endpoint address=\"\" behaviorConfiguration=\"web\" binding=\"webHttpBind" +
                    "ing\"\r\n          name=\"interface");
            
            #line 21 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IntfCode));
            
            #line default
            #line hidden
            this.Write("\" bindingName=\"1\" \r\n        contract=\"TempRestHostService.Interface");
            
            #line 22 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IntfCode));
            
            #line default
            #line hidden
            this.Write("\" />\r\n        <endpoint address=\"mex\" binding=\"mexHttpBinding\" contract=\"IMetadat" +
                    "aExchange\" />\r\n        <host>\r\n          <baseAddresses>\r\n            <add baseA" +
                    "ddress=\"http://127.0.0.1:");
            
            #line 26 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjOption.ProjPort));
            
            #line default
            #line hidden
            this.Write("/Service");
            
            #line 26 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IntfCode));
            
            #line default
            #line hidden
            this.Write("/\" />\r\n          </baseAddresses>\r\n        </host>\r\n      </service>\r\n\t");
            
            #line 30 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    </services>\r\n    <behaviors>\r\n      <serviceBehaviors>\r\n\t    ");
            
            #line 34 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
 foreach (var item in ProjOption.Interfaces) { 
            
            #line default
            #line hidden
            this.Write("        <behavior name=\"TempRestHostSerivce.SB");
            
            #line 35 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IntfCode));
            
            #line default
            #line hidden
            this.Write("\">\r\n          <serviceMetadata httpGetEnabled=\"True\" />\r\n          <serviceDebug " +
                    "includeExceptionDetailInFaults=\"False\" />\r\n        </behavior>\r\n\t\t");
            
            #line 39 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"      </serviceBehaviors>
      <endpointBehaviors>
        <behavior name=""web"">
          <!--部署前改为 false-->
          <webHttp helpEnabled=""true"" />
        </behavior>
        <behavior name=""wcf"">
        </behavior>
      </endpointBehaviors>
    </behaviors>
  </system.serviceModel>
  <runtime>
    <assemblyBinding xmlns=""urn:schemas-microsoft-com:asm.v1"">
      <dependentAssembly>
        <assemblyIdentity name=""Newtonsoft.Json"" publicKeyToken=""30ad4fe6b2a6aeed"" culture=""neutral"" />
        <bindingRedirect oldVersion=""0.0.0.0-10.0.0.0"" newVersion=""10.0.0.0"" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "E:\data\ILAK\ILAK.API\ILAK.API\CodeGenerate\Templates\AppConfigTemplate.tt"

private global::ILAK.API.ProjGenOptions _ProjOptionField;

/// <summary>
/// Access the ProjOption parameter of the template.
/// </summary>
private global::ILAK.API.ProjGenOptions ProjOption
{
    get
    {
        return this._ProjOptionField;
    }
}

private string _HYDAPIConnStringField;

/// <summary>
/// Access the HYDAPIConnString parameter of the template.
/// </summary>
private string HYDAPIConnString
{
    get
    {
        return this._HYDAPIConnStringField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ProjOptionValueAcquired = false;
if (this.Session.ContainsKey("ProjOption"))
{
    this._ProjOptionField = ((global::ILAK.API.ProjGenOptions)(this.Session["ProjOption"]));
    ProjOptionValueAcquired = true;
}
if ((ProjOptionValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ProjOption");
    if ((data != null))
    {
        this._ProjOptionField = ((global::ILAK.API.ProjGenOptions)(data));
    }
}
bool HYDAPIConnStringValueAcquired = false;
if (this.Session.ContainsKey("HYDAPIConnString"))
{
    this._HYDAPIConnStringField = ((string)(this.Session["HYDAPIConnString"]));
    HYDAPIConnStringValueAcquired = true;
}
if ((HYDAPIConnStringValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("HYDAPIConnString");
    if ((data != null))
    {
        this._HYDAPIConnStringField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class AppConfigTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
